/*
    FUNCTION() CONSTRUCTOR

    * Expressão new
    * criar um novo objeto
    * * this keyword


*/

// function Person(name){
//     this.name = name
//     this.walk = function(){
//         return this.name + " está andando"
//     }
// }
// const angelina = new Person("Angelina")
// const joao = new Person("Joao almeira")
// console.log(angelina.walk())
// console.log(joao.walk())

let date = new Date("2020-12-01")

console.log(date)